name: Build

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Please

    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release_please
        with:
          release-type: simple
          pull-request-title-pattern: 'chore${scope}: 🔖 release${component} ${version}'

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Standard
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: |
            mcdrtowhee/mcdreforged:latest
            mcdrtowhee/mcdreforged:${{ needs.release-please.outputs.tag_name }}

      - name: Build and Push Plus
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-plus
          platforms: linux/amd64
          push: true
          tags: |
            mcdrtowhee/mcdreforged:latest-plus
            mcdrtowhee/mcdreforged:${{ needs.release-please.outputs.tag_name }}-plus

      - name: Build and Push Slim
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-slim
          platforms: linux/amd64
          push: true
          tags: |
            mcdrtowhee/mcdreforged:latest-slim
            mcdrtowhee/mcdreforged:${{ needs.release-please.outputs.tag_name }}-slim

      - name: Build and Push Slim Plus
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-slim-plus
          platforms: linux/amd64
          push: true
          tags: |
            mcdrtowhee/mcdreforged:latest-slim-plus
            mcdrtowhee/mcdreforged:${{ needs.release-please.outputs.tag_name }}-slim-plus
